version: '3.8'
services:
  portfolio:
    image: polarkaung1999/next-portfolio-v2-image:latest
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3001
networks:
  default:
    name: nginx-proxy-manager_default
    external: true
