import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/TransitionProvider";
import NavBar from "@/components/Navbar";
import dynamic from "next/dynamic";
import SlideTransition from "@/components/SlideTransition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const NavBar = dynamic(import("@/components/Navbar"))
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <div className="h-24 nav-container z-[10]">
          <NavBar />
        </div>
        {/* <div className="min-h-[calc(100vh-6rem)] flex flex-col relative z-[0]">
          {children}
        </div> */}
        {/* <div className=""> */}
        <SlideTransition>
          {children}
        </SlideTransition>
        {/* </div> */}
      </body>
    </html>
  );
}
